### ISSUE TITLE
Include crash/error reporting tools like Bugsnag

### ISSUE THREAD

**Issue by arximughal** [thecodingmachine/react-native-boilerplate#12]
I've been using this boilerplate for a couple of weeks now and it's really great. You guys have definitely put a lot of effort in building the perfect and industry standard stuff. 

The only thing that I think is missing in this boilerplate is a error/crash reporting tool. I was experimenting with the Bugsnag and integrated it as a service, just like NavigationService and it's doing really good. 

It would be really good to see Bugsnag integrated out of the box

**Comment by JeremyDolle** [comment]
Thanks a lot for your feedback about our boilerplate. Your issue is really interesting but we don't want to be dependent on a product that needs a payment subscription. But, I think it will be really helpful to create a documentation inside `docs` folder, to explain how to integrate this feature.

Thanks again for your kind feedback

**Comment by arximughal** [comment]
Great. No problem :+1: 

I'll close this issue then :smile:
