### ISSUE TITLE
Why removed Redux Saga? 

### ISSUE THREAD

**Issue by crjacinro** [thecodingmachine/react-native-boilerplate#141]
Hi,

I have started a project several months ago using this boilerplate (with Sagas specifically) but in latest version, Sagas was totally removed. Is there any reason why you decided to remove Saga and used Thunk?  I checked the redux-toolkit repo and it uses Thunk internally (please correct me if I am wrong). Is there a migration guide for this?

In general, are there any documentation on how to migrate from old version to v2 version? 

Thank you for your help.

**Comment by JeremyDolle** [comment]
Hi, 
Interesting remark. You're totally right. Saga has been removed from this boilerplate because we now use redux-toolkit. Redux toolkit allow us to create easily redux code and use the thunk middleware so the saga layer becomes unnecessary. In addition we create redux-toolkit-wrapper to be more simple and concise. This is our philosophy for this V2 : the code have to be simple and very easy to use.
I take your comment on the migration from V1. It's a very good idea because the V2 has some breaking changes.
