### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Chimpaya** [thecodingmachine/react-native-boilerplate#156]
Will there be a typescript version for the template? Thank you.

**Comment by JeremyDolle** [comment]
Hi @Chimpaya, we are working on it.

**Comment by fandy** [comment]
Is there a dev branch or ETA for this @JeremyDolle?

**Comment by JeremyDolle** [comment]
Hi @fandy, you have a [branch](https://github.com/thecodingmachine/react-native-boilerplate/tree/ts-support) for that. This is not finished yet but feedbacks are welcome 😉

**Comment by aniruddhashevle** [comment]
@JeremyDolle: Any update on this? Can you please let us know when can we expect a typescript version for the template?

**Comment by JeremyDolle** [comment]
Hi everyone, sorry for the delay I have a lot to do and I have to learn about typescript before doing anything. I found an interesting solution today in order to keep the boilerplate maintainable and provide a user friendly typescript support! When It will be release I will need to have feedbacks on it because I am not an expert; so if you want to contribute don't hesitate to contact me 😉

I hope releasing the typescript support by the end of the month

**Comment by JeremyDolle** [comment]
Hi everyone 👋 

Yesterday we release an alpha version with the typescript support 🚀!! You can try it by running `npx react-native init MyTsApp --template @thecodingmachine/react-native-boilerplate@v3.alpha.1` and choose the typescript version.

Now I need you 🙏! I am not an expert in typescript, so please let me know what we've missed and what we've done wrong. We plan to rewrite `@thecodingmachine/redux-toolkit-wrapper` in typescript to have a better support. 

After that, I will apply some of your advices and make a release.

Hope you will love it ! 💙

**Comment by Cortlandd** [comment]
@JeremyDolle if you have already started your project and its in javascript, but want to switch over to Typescript, how would you go about it?

**Comment by JeremyDolle** [comment]
Hi @Cortlandd, I have no script to merge your changes with the typescript template because it can cause a lot of issues and it could be very hard to maintain. What I recommend, is to go into the template and see what files you have to change [here](https://github.com/thecodingmachine/react-native-boilerplate/tree/master/template/plugins/typescript/template/src). and don't forget to add a the [tsconfig.json](https://github.com/thecodingmachine/react-native-boilerplate/blob/master/template/plugins/typescript/template/tsconfig.example.json)
