### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by thodwris** [thecodingmachine/react-native-boilerplate#16]
Thank you for that!
But why you didn't include web support by utilizing react native for web or using some other technique?

**Comment by AurelGit** [comment]
Hello @thodwris  thanks for your interesting question.

For many reasons we don't want to use some tools like `react-native-for-web`.
The main reason : our point of view is that the conception of a mobile application is completely different from a web site conception.  A mobile application is not a website in an app, with the same functionalities ; it's entirely designed for specific purposes, with a particular user experience.

Thanks again for your feedback.

**Comment by worosom** [comment]
@AurelGit I respect your opinions, but is there any chance you've since changed your mind?

I have a [fork](https://github.com/worosom/react-native-boilerplate) that makes it possible to use all features of this boilerplate with react-native-web, and it works great except that for now the test suite fails due to changes in [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler/pull/1917).
