### ISSUE TITLE
Is it possible to add additional action in one file?

### ISSUE THREAD

**Issue by rosnaib11** [thecodingmachine/react-native-boilerplate#162]
Is it necessary to create separate file of new state module?

> We've decided to separate each module in one file in order to avoid very large incomprehensible files. So each of them includes its scoped state, his only action and related reducers.

Because I want to add additional action for logout to update the isAuth: to true or false using separate action `'user/logout'`

Index
```
import { buildSlice } from '@thecodingmachine/redux-toolkit-wrapper'
import FetchOne from './FetchOne'
import Logout from './Logout'

// This state is common to all the "user" module, and can be modified by any "user" reducers
const sliceInitialState = {
  item: {},
  isAuth: false,
}

export default buildSlice('user', [FetchOne, Logout], sliceInitialState).reducer
``` 

FetchOne.js
```
import {
  buildAsyncState,
  buildAsyncReducers,
  buildAsyncActions,
} from '@thecodingmachine/redux-toolkit-wrapper'
import fetchOneUserService from '@/Services/User/FetchOne'

export default {
  initialState: buildAsyncState('fetchOne'),
  action: buildAsyncActions([ // something like this
    'user/fetchOne': function(){
          //...
    }
  ]),  
  reducers: buildAsyncReducers({
    errorKey: 'fetchOne.error', // Optionally, if you scoped variables, you can use a key with dot notation
    loadingKey: 'fetchOne.loading',
  }),
}
```

So far what I'm doing is to create separate file for logout, Logout.js. And just added it to index.js. This works fine but i'm not sure if its possible to just include it to my fetchOne.js for example.

```
import { createAction } from '@reduxjs/toolkit'

export default {
  initialState: {},
  action: createAction('user/logout'),
  reducers(state, { payload }) {
    state.item = {}
    state.isAuth = false
  },
}
```

Thanks

**Comment by JeremyDolle** [comment]
Hi @rosnaib11, Nice question, we recommend separate by file because it gives you a clear and readable code. If you separate your files, the architecture becomes clear and understandable : `user/FetchOne.js` is about a fetch of one user, and `user/logout` is about disconnecting the user. 

If I understand well, you want to "hide" the `logout` module into the `fetchOne` one. So the architecture, to my mind, is not ideal because I cannot find `Logout` feature easily. But, the thing you can do is having an `index.js` file in `user` folder and put all your actions here like this : 

```
import {
  buildAsyncState,
  buildAsyncReducers,
  buildAsyncActions,
} from '@thecodingmachine/redux-toolkit-wrapper'
import fetchOneUserService from '@/Services/User/FetchOne'
import { createAction } from '@reduxjs/toolkit'

const FetchOne = {
  initialState: buildAsyncState('fetchOne'),
  action: buildAsyncActions([ // something like this
    'user/fetchOne': function(){
          //...
    }
  ]),  
  reducers: buildAsyncReducers({
    errorKey: 'fetchOne.error', // Optionally, if you scoped variables, you can use a key with dot notation
    loadingKey: 'fetchOne.loading',
  }),
}

const Logout = {
  initialState: {},
  action: createAction('user/logout'),
  reducers(state, { payload }) {
    state.item = {}
    state.isAuth = false
  },
}

// This state is common to all the "user" module, and can be modified by any "user" reducers
const sliceInitialState = {
  item: {},
  isAuth: false,
}

export default buildSlice('user', [FetchOne, Logout], sliceInitialState).reducer
```

We decided to separate into different files in order to understand the code without open any file and prepare it for the future. For exemple if the user slice have more modules like FetchMany, Delete, Add, Switch... you will have a very big and difficult to read file.

Hope it's help 😉

**Comment by rosnaib11** [comment]
Ok thanks this is cool
