### ISSUE TITLE
[Win10] Cannot run on Android 

### ISSUE THREAD

**Issue by kelvin-dev** [thecodingmachine/react-native-boilerplate#18]
Plz help check, our prototype project based upon your starter-kit and seems that the boilerplate doesnt work properly. Tons of thanks
![image](https://user-images.githubusercontent.com/19224355/49349589-e8476b00-f6dd-11e8-8203-b07115f5a010.png)

**Comment by kelvin-dev** [comment]
D:\Demos\react-native-boilerplate>react-native info

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 1.17 GB / 7.83 GB
    Binaries:
yarn install v0.15.1
success Already up-to-date.
Done in 0.15s. - D:\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by kelvin-dev** [comment]
Plz help integrate this into the boilerplate, current approach is NOT good against the community's status quo. Tons of thanks
https://github.com/luggit/react-native-config.git

**Comment by kelvin-dev** [comment]
The sample API - https://query.yahooapis.com/v1/public/ is dead, plz help update also

**Comment by JeremyDolle** [comment]
Hi @kelvin-dev, this [librairie](https://github.com/luggit/react-native-config.git) wasn't working since React-Native 0.56 (there are always [issues](https://github.com/luggit/react-native-config/issues?utf8=%E2%9C%93&q=0.56) about that). So, we decided to make a config file to be able to work with React-Native 0.56. 

Did you `create your configuration file App/Config/index.js from index.dev.js (in you are in dev environment) and fill the missing values` ?

Also, the sample API isn't dead for me :
![image](https://user-images.githubusercontent.com/15814069/49361278-dbc21300-f6db-11e8-9b46-caa3b525a543.png)

Hope it will help you.

**Comment by tstkenny** [comment]
I am quite new to the repo and I cannot make it work on API 23 emulator or a physical Android 5 devices.  The app crashes once loaded, without any react native red background error.  Would appreciate if you can take a look.

react-native run-android completes without any error in console though.

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
      Memory: 7.60 GB / 15.96 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809
