### ISSUE TITLE
Need Authorization Flow

### ISSUE THREAD

**Issue by tcagkansokmen** [thecodingmachine/react-native-boilerplate#185]
This is the best boilerplate for react native. And thank you so much.

But I guess, we need to see authorization flow in that.

User logs in, and we save token.
If token is expired or removed, user redirects to login screen.
Token is kept even application is closed.

I have tried to make that flow, but doesnt work any stable.
I keep token, but when open application, it redirects to login screen and after that auto redirect to main page. (I must remove login flow at that point)

It would be great to see that by you.
I hope, you add.

**Comment by JeremyDolle** [comment]
Hi @tcagkansokmen, thank you for using this boilerplate and give feedback about it !

We have a lot of discussion about implementing that feature or not because an authentication can be done with token but also with session... Our code of conduct about this boilerplate is to not restrict the user to a way or to a dependency when he or she will use it.

We will talk about it internally and see if we can find a way to provide a good solution !

Thanks again for using this boilerplate.

**Comment by mtalhagaoglu** [comment]
Hi @JeremyDolle , is there any updates on this topic? Did you decide what you will do or not? Btw you are right about restriction about token or session but probably token is much more usable

**Comment by aashari** [comment]
I am also interested in this feature

**Comment by jinman** [comment]
Any update on how we can create a Authorization or Authentication Flow. Looks like React Navigation has some of this features already. Thoughts on best way to implement Login, Token, Save Password, Webview?
