### ISSUE TITLE
React navigation example?

### ISSUE THREAD

**Issue by tstkenny** [thecodingmachine/react-native-boilerplate#23]
Many developers came here since they want to enjoy a carefully crafted RN boilerplate, if it can also provide some best-practice kitchen such as how to implement navigation with redux would be awesome!

**Comment by AurelGit** [comment]
Hello @tstkenny !

You're right, using navigation in a redux environment is not the easiest thing.

Just to be clear, in this boilerplate we do not provide any way to have navigation state stored in the same place as the rest of application state.
Because it's now deprecated and will no longer be maintained in react-navigation, [as described here](https://reactnavigation.org/docs/en/redux-integration.html).

To  perform navigation actions from outside of your components (eg: from a Redux middleware, and in our case from Redux Saga middleware), we provided a [NavigationService](https://github.com/thecodingmachine/react-native-boilerplate/blob/master/App/Services/NavigationService.js) which can be used to navigate inside sagas.

You can find a example in the [startup saga](https://github.com/thecodingmachine/react-native-boilerplate/blob/master/App/Sagas/StartupSaga.js).
When all operations are finished, you can navigate into the main screen with : 
```javascript
  // When those operations are finished we redirect to the main screen
  NavigationService.navigateAndReset('MainScreen')
```

As described in the NavigationService file, you can use two methods, `navigate` or `navigateAndReset` : 
```javascript
...

/**
 * Call this function when you want to navigate to a specific route.
 *
 * @param routeName The name of the route to navigate to. Routes are defined in RootScreen using createStackNavigator()
 * @param params Route parameters.
 */
function navigate(routeName, params) 


...

/**
 * Call this function when you want to navigate to a specific route AND reset the navigation history.
 *
 * That means the user cannot go back. This is useful for example to redirect from a splashscreen to
 * the main screen: the user should not be able to go back to the splashscreen.
 *
 * @param routeName The name of the route to navigate to. Routes are defined in RootScreen using createStackNavigator()
 * @param params Route parameters.
 */
function navigateAndReset(routeName, params)
```

Thank you for your feedback, I hope this will help you !
