### ISSUE TITLE
Warning on running develop: new NativeEventEmitter()

### ISSUE THREAD

**Issue by quangtam** [thecodingmachine/react-native-boilerplate#231]
Hi,

I've setup and I've got WARNING when running android:
` WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method. 
App
RCTView
View
RCTView
View`

Please help me to resolve.
Thanks & best regards,

**Comment by JeremyDolle** [comment]
Yes, I know, I think the issue comes from the `Provider` component of `react-redux`. If you comment it, the warning disappear. 
![image](https://user-images.githubusercontent.com/15814069/135269118-a771d389-4dde-4644-af65-443febfa985e.png)

Btw, it's just a warning, every thing seems to run perfectly no ? We will have to wait an update.

**Comment by JeremyDolle** [comment]
I found that the issue comes from redux-flipper in fact ! I will investigate 😉

**Comment by quangtam** [comment]
> I found that the issue comes from redux-flipper in fact ! I will investigate 😉

Waiting for your help! Thanks @JeremyDolle

**Comment by JeremyDolle** [comment]
> > I found that the issue comes from redux-flipper in fact ! I will investigate 😉
> 
> Waiting for your help! Thanks @JeremyDolle

So, In `Store/index.js` in the function `configureStore` there is an issue in the `middleware` parameter. instead of       `middlewares.push(createDebugger())` replace by `middlewares.concat(createDebugger())`.

I currently working on a new version of the boilerplate with RN 0.66 and RTK query and I make this fix. I hope release it quickly !

Let me know if it's working.

**Comment by JeremyDolle** [comment]
After a few tests, the "concat fix" doesn't work. We have to deal with it until an update 😉

**Comment by daipham3213** [comment]
> 

thank you. it did the trick
