### ISSUE TITLE
not an issue but an idea

### ISSUE THREAD

**Issue by davingee** [thecodingmachine/react-native-boilerplate#24]
instead of having to update the config file all the time, would using an env variable work??
```
const default_config = {
  default:        true,
  response_type:  'json',
  env:            'should_override'
}

if (process.env['NODE_ENV'] == 'development'){
  env_config = {
    api_url:  'https://query.yahooapis.com/v1/public/',
    env:      'development',
  }
} else {
  env_config = {
    api_url:  'https://query.yahooapis.com/v1/public/',
    env:      'production',
  }
}

export const Config = Object.assign(default_config, env_config);

```

**Comment by AurelGit** [comment]
Hello @davingee !

Thanks for your feedback.

I think you're right, there is something to do better with configuration files. 
I'm currently working on a new feature, to make it works properly with fastlane, and avoid switching files when deploying app.

So I keep your idea in mind, I let your ticket openned, and I will ping you as soon as my new PR is opened for review !

**Comment by AurelGit** [comment]
P.S : all our deployment are made with Fastlane according to this documentation : https://github.com/thecodingmachine/react-native-boilerplate/blob/master/docs/beta%20builds.md

**Comment by AurelGit** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue or need to implement this feature.

Thank you!
