### ISSUE TITLE
Obfuscate code

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#257]
**Is your feature request related to a problem? Please describe.**
Obfuscate the code so that the class and components are not easy to read.

**Additional context**

@JeremyDolle : 
https://stackoverflow.com/a/64347516/8024296
https://stackoverflow.com/a/54282723/8024296
https://stackoverflow.com/a/69202010/8024296

**Comment by Angelk90** [comment]
@JeremyDolle : Are there any news?

**Comment by Angelk90** [comment]
@JeremyDolle : Are there any news?

**Comment by JeremyDolle** [comment]
Hello @Angelk90 

This feature will not be implemented in this boilerplate because it is not a requirement for every user. BUT !
I was working on a `custom plugin layer` till last year. In January, I made an PR on the react native cli to make it easier because it' a really Challenging feature. The PR is still opened so I worked to find an alternative to release the feature without the resolution of the PR and I just found it last week! 

The idea of the `custom plugin layer` is to provide, during the installation, the choice to the user to use a "custom plugin". A custom plugin is a set of feature to add to the original boilerplate like a login flow, a config to obfuscate the code and all other specific feature.
This can let people contribute to the boilerplate through plugins. Like that the boilerplate is still a light boilerplate with no extra feature and the community is not frustrated by a missing feature for us. 

A Typescript library will be realized to help plugins creators with a set of function in order to be able to create a plugin easily with a template repository.

I will probably release a beta version soon 🤞🤞🤞

**Comment by Angelk90** [comment]
@JeremyDolle : Are you referring to this: https://github.com/react-native-community/cli/pull/1526

**Comment by JeremyDolle** [comment]
yes

**Comment by Angelk90** [comment]
@JeremyDolle : I saw that the pr was accepted, is there any news?

**Comment by JeremyDolle** [comment]
We hate to wait the new version of the cli

**Comment by Angelk90** [comment]
@JeremyDolle : is there any news?

**Comment by Angelk90** [comment]
.
