### ISSUE TITLE
Upgrade to RN69 

### ISSUE THREAD

**Issue by elirangoshen** [thecodingmachine/react-native-boilerplate#304]
### Is your feature request related to a problem?

I just upgrade to RN69 and it took loooong time :)

### Describe the solution you'd like

would be nice to have new version to boilerplate with RN69 installed to make it easy for future users.

**Comment by JeremyDolle** [comment]
Hi @elirangoshen, It's in the roadmap but it seems that some librairies are not yet ready to be working with the new architecture so we delay a bit the version update. What's your opinion about it ?

**Comment by SuperRoach** [comment]
Just done a few 68 to 69 upgrades, and it's been a royal mess. The pain is worth it though:

The hermes compiler makes for smaller and faster runtimes, it's great. It's come a long way since the introduction in .65.

A big help (besides the RN guide to doing so), is the upgrade helper: https://react-native-community.github.io/upgrade-helper/ you can put in this version and check it out.

It feels a bit odd also basing it on a version of RN that's already a year old before you start your boilerplate out. I can see XCode phasing out that minimum version as ios 16 comes out - why make for more pain when starting from scratch?

I'd advise that if you can, to not eject - allow the user to do it (it's only one step), It gives the user the choice if they know they need to do it.

**Comment by JeremyDolle** [comment]
Thanks for the advice. I already done the upgrade, let me know (reopen the issue) if you have some feedbacks
