### ISSUE TITLE
Did yarn rename, but now app crashes as soon as it starts.

### ISSUE THREAD

**Issue by Zabi-Progton** [thecodingmachine/react-native-boilerplate#84]
I have update the libraries to the latest compatible versions and made necessary changes in the code but after renaming the project the app doesn't seem to even load. Gets stuck at loading dependency graph.

**Comment by om-mahato** [comment]
Having same issue :-/
"Did yarn rename, but now app crashes as soon as it starts."

**Comment by stephyswe** [comment]
Unsupported class file major version 57

**Comment by Floridus** [comment]
@Zabi-Progton @om-mahato 
I had the same mistake. That was because with me then the two Java files were no longer there, since there was now a new package. Thus, there was no more MainActivity class.

- Look at `android/app/src/main/java/com/{your-new-package-name}`. Are there the two files `MainActivity.java` and `MainApplication.java`?
- If not, then you should add them again, just copy them out of the repo again. That was my solution.

@stephyswe your error is that you should use JDK 8 and not a newer JDK version. I used at the beginning JDK 13 and I got the same error. With JDK 8 it is working.

**Comment by AurelGit** [comment]
Rename is now not useful on the new implementation of the boilerplate !

You can directly use : 
```
npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate
```
