### ISSUE TITLE
Why not expo and how to upgrade native afterward ?

### ISSUE THREAD

**Issue by kopax** [thecodingmachine/react-native-boilerplate#86]
Hi guys, I am parisien aussi and pleased that I have found a boilerplate to get started with react-native. I have never developed react-native application before but I am considering making one with your boilerplate. I use ReactJS, redux, saga so it would make sense to start with native for a simple app. 

Current [React-Native version is v0.61.1](https://github.com/facebook/react-native/releases) while this repository use `v0.60.5`.

I am reading react-native documentation and I have read the upgrade react-native guide. 
I wonder if there is a strategy in this repo for doing that because I have not seen anything in the `README.md`. 

I have read your README and I really like the bundle you have made, especially the **fastlane tools** integrated.

The documentation is poor, so I ask for advice on how to get started with the boilerplate.

- Why not expo (honest question)
- is there a migration strategy here?
- is there a documentation for this project?
- is there any other advice I could get from the coding machine before getting my hand dirty ?
- Do you recommend fastlane for newcomer in native development (iOS and Android) or you recommend to get started with the basic first?

Thanks for sharing,

**Comment by JeremyDolle** [comment]
Hi @kopax, we just release the V2 of this boilerplate you can take a look. To answer your questions : 

> Why not expo (honest question)

Because with bare project we have less limitation. Moreover, we can use expo libraries in bare projects so we find that's bare project can be applied  to all type of application.

> is there a migration strategy here?

Is up to date now in V2, we will keep the projet up to date.

> is there a documentation for this project?

You can find it [here](https://thecodingmachine.github.io/react-native-boilerplate) it is in Work In Progress

> is there any other advice I could get from the coding machine before getting my hand dirty ?

Our doc describe some guides to do maintainable app

> Do you recommend fastlane for newcomer in native development (iOS and Android) or you recommend to get started with the basic first?

Why not using it ? It a very nice tool ;)
